<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        
    }

    function index()
    {
        $data['_view'] = 'dashboard';
        $data['cur_uri'] = 'dashboard';
        $data['breadcrumb_title'] = 'Dashboard';
        $data['breadcrumb_item'] = '';
        $data['page_title'] = 'Dashboard'; 
        $this->load->view('layouts/main',$data);
    }
}
